[workspace]
members = [
    "benches",
    "frontend",
    "frontend_debug",
    "frontend_web",
    "gameboy",
    "test/junit_to_md"
]
default-members = [
    "frontend",
    "gameboy",
]

[profile.dev]
opt-level = 3
overflow-checks = false

[profile.release]
lto = true
panic = "abort"
codegen-units = 1

[profile.test]
opt-level = 3
overflow-checks = false

[profile.ci]
inherits = "dev"
opt-level = 1
