use super::alu::{Rl, Rlc, Rr, Rrc, Sla, Sra, Srl, Swap};
use super::instruction::{Instruction, InstructionOpcode};
use super::opcodes::*;
use super::regs::cond::{Carry, NZ, NotCarry, Z};
use super::regs::{A, AF, B, BC, C, D, DE, E, H, HL, L, SP};

pub struct InstructionCache {
    interrupt_service_routine: Instruction,
    instructions: [Instruction; 256],
    cb_instructions: [Instruction; 256],
}

impl Default for InstructionCache {
    fn default() -> Self {
        Self::new()
    }
}

impl InstructionCache {
    pub fn new() -> Self {
        Self {
            interrupt_service_routine: interrupt_service_routine(),
            instructions: Self::gen_instructions(),
            cb_instructions: Self::gen_cb_instructions(),
        }
    }

    fn gen_instructions() -> [Instruction; 256] {
        [
            // 0x00 - 0x0F
            nop(),
            ld_r16_u16::<BC>(),
            ld_mem_a::<BC>(),
            inc_r16::<BC>(),
            inc_r8::<B>(),
            dec_r8::<B>(),
            ld_r8_u8::<B>(),
            rlca(),
            ld_u16_sp(),
            add_hl_r16::<BC>(),
            ld_a_mem::<BC>(),
            dec_r16::<BC>(),
            inc_r8::<C>(),
            dec_r8::<C>(),
            ld_r8_u8::<C>(),
            rrca(),
            // 0x10 - 0x1F
            stop(),
            ld_r16_u16::<DE>(),
            ld_mem_a::<DE>(),
            inc_r16::<DE>(),
            inc_r8::<D>(),
            dec_r8::<D>(),
            ld_r8_u8::<D>(),
            rla(),
            jr_i8(),
            add_hl_r16::<DE>(),
            ld_a_mem::<DE>(),
            dec_r16::<DE>(),
            inc_r8::<E>(),
            dec_r8::<E>(),
            ld_r8_u8::<E>(),
            rra(),
            // 0x20 - 0x2F
            jr_cc_i8::<NZ>(),
            ld_r16_u16::<HL>(),
            ld_mem_a_hl_inc(),
            inc_r16::<HL>(),
            inc_r8::<H>(),
            dec_r8::<H>(),
            ld_r8_u8::<H>(),
            daa(),
            jr_cc_i8::<Z>(),
            add_hl_r16::<HL>(),
            ld_a_mem_hl_inc(),
            dec_r16::<HL>(),
            inc_r8::<L>(),
            dec_r8::<L>(),
            ld_r8_u8::<L>(),
            cpl(),
            // 0x30 - 0x3F
            jr_cc_i8::<NotCarry>(),
            ld_r16_u16::<SP>(),
            ld_mem_a_hl_dec(),
            inc_r16::<SP>(),
            inc_hlmem(),
            dec_hlmem(),
            ld_hlmem_u8(),
            scf(),
            jr_cc_i8::<Carry>(),
            add_hl_r16::<SP>(),
            ld_a_mem_hl_dec(),
            dec_r16::<SP>(),
            inc_r8::<A>(),
            dec_r8::<A>(),
            ld_r8_u8::<A>(),
            ccf(),
            // 0x40 - 0x4F: LD B, r8 / LD C, r8
            ld_r8_r8::<B, B>(),
            ld_r8_r8::<B, C>(),
            ld_r8_r8::<B, D>(),
            ld_r8_r8::<B, E>(),
            ld_r8_r8::<B, H>(),
            ld_r8_r8::<B, L>(),
            ld_r8_hlmem::<B>(),
            ld_r8_r8::<B, A>(),
            ld_r8_r8::<C, B>(),
            ld_r8_r8::<C, C>(),
            ld_r8_r8::<C, D>(),
            ld_r8_r8::<C, E>(),
            ld_r8_r8::<C, H>(),
            ld_r8_r8::<C, L>(),
            ld_r8_hlmem::<C>(),
            ld_r8_r8::<C, A>(),
            // 0x50 - 0x5F: LD D, r8 / LD E, r8
            ld_r8_r8::<D, B>(),
            ld_r8_r8::<D, C>(),
            ld_r8_r8::<D, D>(),
            ld_r8_r8::<D, E>(),
            ld_r8_r8::<D, H>(),
            ld_r8_r8::<D, L>(),
            ld_r8_hlmem::<D>(),
            ld_r8_r8::<D, A>(),
            ld_r8_r8::<E, B>(),
            ld_r8_r8::<E, C>(),
            ld_r8_r8::<E, D>(),
            ld_r8_r8::<E, E>(),
            ld_r8_r8::<E, H>(),
            ld_r8_r8::<E, L>(),
            ld_r8_hlmem::<E>(),
            ld_r8_r8::<E, A>(),
            // 0x60 - 0x6F: LD H, r8 / LD L, r8
            ld_r8_r8::<H, B>(),
            ld_r8_r8::<H, C>(),
            ld_r8_r8::<H, D>(),
            ld_r8_r8::<H, E>(),
            ld_r8_r8::<H, H>(),
            ld_r8_r8::<H, L>(),
            ld_r8_hlmem::<H>(),
            ld_r8_r8::<H, A>(),
            ld_r8_r8::<L, B>(),
            ld_r8_r8::<L, C>(),
            ld_r8_r8::<L, D>(),
            ld_r8_r8::<L, E>(),
            ld_r8_r8::<L, H>(),
            ld_r8_r8::<L, L>(),
            ld_r8_hlmem::<L>(),
            ld_r8_r8::<L, A>(),
            // 0x70 - 0x7F: LD (HL), r8 / HALT / LD A, r8
            ld_hlmem_r8::<B>(),
            ld_hlmem_r8::<C>(),
            ld_hlmem_r8::<D>(),
            ld_hlmem_r8::<E>(),
            ld_hlmem_r8::<H>(),
            ld_hlmem_r8::<L>(),
            halt(),
            ld_hlmem_r8::<A>(),
            ld_r8_r8::<A, B>(),
            ld_r8_r8::<A, C>(),
            ld_r8_r8::<A, D>(),
            ld_r8_r8::<A, E>(),
            ld_r8_r8::<A, H>(),
            ld_r8_r8::<A, L>(),
            ld_r8_hlmem::<A>(),
            ld_r8_r8::<A, A>(),
            // 0x80 - 0x8F: ADD / ADC
            add_a_r8::<B>(),
            add_a_r8::<C>(),
            add_a_r8::<D>(),
            add_a_r8::<E>(),
            add_a_r8::<H>(),
            add_a_r8::<L>(),
            add_a_hlmem(),
            add_a_r8::<A>(),
            adc_a_r8::<B>(),
            adc_a_r8::<C>(),
            adc_a_r8::<D>(),
            adc_a_r8::<E>(),
            adc_a_r8::<H>(),
            adc_a_r8::<L>(),
            adc_a_hlmem(),
            adc_a_r8::<A>(),
            // 0x90 - 0x9F: SUB / SBC
            sub_a_r8::<B>(),
            sub_a_r8::<C>(),
            sub_a_r8::<D>(),
            sub_a_r8::<E>(),
            sub_a_r8::<H>(),
            sub_a_r8::<L>(),
            sub_a_hlmem(),
            sub_a_r8::<A>(),
            sbc_a_r8::<B>(),
            sbc_a_r8::<C>(),
            sbc_a_r8::<D>(),
            sbc_a_r8::<E>(),
            sbc_a_r8::<H>(),
            sbc_a_r8::<L>(),
            sbc_a_hlmem(),
            sbc_a_r8::<A>(),
            // 0xA0 - 0xAF: AND / XOR
            and_a_r8::<B>(),
            and_a_r8::<C>(),
            and_a_r8::<D>(),
            and_a_r8::<E>(),
            and_a_r8::<H>(),
            and_a_r8::<L>(),
            and_a_hlmem(),
            and_a_r8::<A>(),
            xor_a_r8::<B>(),
            xor_a_r8::<C>(),
            xor_a_r8::<D>(),
            xor_a_r8::<E>(),
            xor_a_r8::<H>(),
            xor_a_r8::<L>(),
            xor_a_hlmem(),
            xor_a_r8::<A>(),
            // 0xB0 - 0xBF: OR / CP
            or_a_r8::<B>(),
            or_a_r8::<C>(),
            or_a_r8::<D>(),
            or_a_r8::<E>(),
            or_a_r8::<H>(),
            or_a_r8::<L>(),
            or_a_hlmem(),
            or_a_r8::<A>(),
            cp_a_r8::<B>(),
            cp_a_r8::<C>(),
            cp_a_r8::<D>(),
            cp_a_r8::<E>(),
            cp_a_r8::<H>(),
            cp_a_r8::<L>(),
            cp_a_hlmem(),
            cp_a_r8::<A>(),
            // 0xC0 - 0xCF
            ret_cc::<NZ>(),
            pop_r16::<BC>(),
            jp_cc_u16::<NZ>(),
            jp_u16(),
            call_cc_u16::<NZ>(),
            push_r16::<BC>(),
            add_a_imm8(),
            rst::<0x00>(),
            ret_cc::<Z>(),
            ret(),
            jp_cc_u16::<Z>(),
            cb_prefix_stub(),
            call_cc_u16::<Z>(),
            call_u16(),
            adc_a_imm8(),
            rst::<0x08>(),
            // 0xD0 - 0xDF
            ret_cc::<NotCarry>(),
            pop_r16::<DE>(),
            jp_cc_u16::<NotCarry>(),
            unused_opcode::<0xD3>(),
            call_cc_u16::<NotCarry>(),
            push_r16::<DE>(),
            sub_a_imm8(),
            rst::<0x10>(),
            ret_cc::<Carry>(),
            reti(),
            jp_cc_u16::<Carry>(),
            unused_opcode::<0xDB>(),
            call_cc_u16::<Carry>(),
            unused_opcode::<0xDD>(),
            sbc_a_imm8(),
            rst::<0x18>(),
            // 0xE0 - 0xEF
            ld_ff00_u8_a(),
            pop_r16::<HL>(),
            ld_ff00_c_a(),
            unused_opcode::<0xE3>(),
            unused_opcode::<0xE4>(),
            push_r16::<HL>(),
            and_a_imm8(),
            rst::<0x20>(),
            add_sp_i8(),
            jp_hl(),
            ld_mem_u16_a(),
            unused_opcode::<0xEB>(),
            unused_opcode::<0xEC>(),
            unused_opcode::<0xED>(),
            xor_a_imm8(),
            rst::<0x28>(),
            // 0xF0 - 0xFF
            ld_a_ff00_u8(),
            pop_r16::<AF>(),
            ld_a_ff00_c(),
            di(),
            unused_opcode::<0xF4>(),
            push_r16::<AF>(),
            or_a_imm8(),
            rst::<0x30>(),
            ld_hl_sp_i8(),
            ld_sp_hl(),
            ld_a_mem_u16(),
            ei(),
            unused_opcode::<0xFC>(),
            unused_opcode::<0xFD>(),
            cp_a_imm8(),
            rst::<0x38>(),
        ]
    }

    fn gen_cb_instructions() -> [Instruction; 256] {
        [
            // 0x00 - 0x3F: RLC / RRC / RL / RR / SLA / SRA / SWAP / SRL
            cb_op_r8::<Rlc, B>(),
            cb_op_r8::<Rlc, C>(),
            cb_op_r8::<Rlc, D>(),
            cb_op_r8::<Rlc, E>(),
            cb_op_r8::<Rlc, H>(),
            cb_op_r8::<Rlc, L>(),
            cb_op_hlmem::<Rlc>(),
            cb_op_r8::<Rlc, A>(),
            cb_op_r8::<Rrc, B>(),
            cb_op_r8::<Rrc, C>(),
            cb_op_r8::<Rrc, D>(),
            cb_op_r8::<Rrc, E>(),
            cb_op_r8::<Rrc, H>(),
            cb_op_r8::<Rrc, L>(),
            cb_op_hlmem::<Rrc>(),
            cb_op_r8::<Rrc, A>(),
            cb_op_r8::<Rl, B>(),
            cb_op_r8::<Rl, C>(),
            cb_op_r8::<Rl, D>(),
            cb_op_r8::<Rl, E>(),
            cb_op_r8::<Rl, H>(),
            cb_op_r8::<Rl, L>(),
            cb_op_hlmem::<Rl>(),
            cb_op_r8::<Rl, A>(),
            cb_op_r8::<Rr, B>(),
            cb_op_r8::<Rr, C>(),
            cb_op_r8::<Rr, D>(),
            cb_op_r8::<Rr, E>(),
            cb_op_r8::<Rr, H>(),
            cb_op_r8::<Rr, L>(),
            cb_op_hlmem::<Rr>(),
            cb_op_r8::<Rr, A>(),
            cb_op_r8::<Sla, B>(),
            cb_op_r8::<Sla, C>(),
            cb_op_r8::<Sla, D>(),
            cb_op_r8::<Sla, E>(),
            cb_op_r8::<Sla, H>(),
            cb_op_r8::<Sla, L>(),
            cb_op_hlmem::<Sla>(),
            cb_op_r8::<Sla, A>(),
            cb_op_r8::<Sra, B>(),
            cb_op_r8::<Sra, C>(),
            cb_op_r8::<Sra, D>(),
            cb_op_r8::<Sra, E>(),
            cb_op_r8::<Sra, H>(),
            cb_op_r8::<Sra, L>(),
            cb_op_hlmem::<Sra>(),
            cb_op_r8::<Sra, A>(),
            cb_op_r8::<Swap, B>(),
            cb_op_r8::<Swap, C>(),
            cb_op_r8::<Swap, D>(),
            cb_op_r8::<Swap, E>(),
            cb_op_r8::<Swap, H>(),
            cb_op_r8::<Swap, L>(),
            cb_op_hlmem::<Swap>(),
            cb_op_r8::<Swap, A>(),
            cb_op_r8::<Srl, B>(),
            cb_op_r8::<Srl, C>(),
            cb_op_r8::<Srl, D>(),
            cb_op_r8::<Srl, E>(),
            cb_op_r8::<Srl, H>(),
            cb_op_r8::<Srl, L>(),
            cb_op_hlmem::<Srl>(),
            cb_op_r8::<Srl, A>(),
            // 0x40 - 0x7F: BIT n, r
            bit::<0, B>(),
            bit::<0, C>(),
            bit::<0, D>(),
            bit::<0, E>(),
            bit::<0, H>(),
            bit::<0, L>(),
            bit_hlmem::<0>(),
            bit::<0, A>(),
            bit::<1, B>(),
            bit::<1, C>(),
            bit::<1, D>(),
            bit::<1, E>(),
            bit::<1, H>(),
            bit::<1, L>(),
            bit_hlmem::<1>(),
            bit::<1, A>(),
            bit::<2, B>(),
            bit::<2, C>(),
            bit::<2, D>(),
            bit::<2, E>(),
            bit::<2, H>(),
            bit::<2, L>(),
            bit_hlmem::<2>(),
            bit::<2, A>(),
            bit::<3, B>(),
            bit::<3, C>(),
            bit::<3, D>(),
            bit::<3, E>(),
            bit::<3, H>(),
            bit::<3, L>(),
            bit_hlmem::<3>(),
            bit::<3, A>(),
            bit::<4, B>(),
            bit::<4, C>(),
            bit::<4, D>(),
            bit::<4, E>(),
            bit::<4, H>(),
            bit::<4, L>(),
            bit_hlmem::<4>(),
            bit::<4, A>(),
            bit::<5, B>(),
            bit::<5, C>(),
            bit::<5, D>(),
            bit::<5, E>(),
            bit::<5, H>(),
            bit::<5, L>(),
            bit_hlmem::<5>(),
            bit::<5, A>(),
            bit::<6, B>(),
            bit::<6, C>(),
            bit::<6, D>(),
            bit::<6, E>(),
            bit::<6, H>(),
            bit::<6, L>(),
            bit_hlmem::<6>(),
            bit::<6, A>(),
            bit::<7, B>(),
            bit::<7, C>(),
            bit::<7, D>(),
            bit::<7, E>(),
            bit::<7, H>(),
            bit::<7, L>(),
            bit_hlmem::<7>(),
            bit::<7, A>(),
            // 0x80 - 0xBF: RES n, r
            res::<0, B>(),
            res::<0, C>(),
            res::<0, D>(),
            res::<0, E>(),
            res::<0, H>(),
            res::<0, L>(),
            res_hlmem::<0>(),
            res::<0, A>(),
            res::<1, B>(),
            res::<1, C>(),
            res::<1, D>(),
            res::<1, E>(),
            res::<1, H>(),
            res::<1, L>(),
            res_hlmem::<1>(),
            res::<1, A>(),
            res::<2, B>(),
            res::<2, C>(),
            res::<2, D>(),
            res::<2, E>(),
            res::<2, H>(),
            res::<2, L>(),
            res_hlmem::<2>(),
            res::<2, A>(),
            res::<3, B>(),
            res::<3, C>(),
            res::<3, D>(),
            res::<3, E>(),
            res::<3, H>(),
            res::<3, L>(),
            res_hlmem::<3>(),
            res::<3, A>(),
            res::<4, B>(),
            res::<4, C>(),
            res::<4, D>(),
            res::<4, E>(),
            res::<4, H>(),
            res::<4, L>(),
            res_hlmem::<4>(),
            res::<4, A>(),
            res::<5, B>(),
            res::<5, C>(),
            res::<5, D>(),
            res::<5, E>(),
            res::<5, H>(),
            res::<5, L>(),
            res_hlmem::<5>(),
            res::<5, A>(),
            res::<6, B>(),
            res::<6, C>(),
            res::<6, D>(),
            res::<6, E>(),
            res::<6, H>(),
            res::<6, L>(),
            res_hlmem::<6>(),
            res::<6, A>(),
            res::<7, B>(),
            res::<7, C>(),
            res::<7, D>(),
            res::<7, E>(),
            res::<7, H>(),
            res::<7, L>(),
            res_hlmem::<7>(),
            res::<7, A>(),
            // 0xC0 - 0xFF: SET n, r
            set::<0, B>(),
            set::<0, C>(),
            set::<0, D>(),
            set::<0, E>(),
            set::<0, H>(),
            set::<0, L>(),
            set_hlmem::<0>(),
            set::<0, A>(),
            set::<1, B>(),
            set::<1, C>(),
            set::<1, D>(),
            set::<1, E>(),
            set::<1, H>(),
            set::<1, L>(),
            set_hlmem::<1>(),
            set::<1, A>(),
            set::<2, B>(),
            set::<2, C>(),
            set::<2, D>(),
            set::<2, E>(),
            set::<2, H>(),
            set::<2, L>(),
            set_hlmem::<2>(),
            set::<2, A>(),
            set::<3, B>(),
            set::<3, C>(),
            set::<3, D>(),
            set::<3, E>(),
            set::<3, H>(),
            set::<3, L>(),
            set_hlmem::<3>(),
            set::<3, A>(),
            set::<4, B>(),
            set::<4, C>(),
            set::<4, D>(),
            set::<4, E>(),
            set::<4, H>(),
            set::<4, L>(),
            set_hlmem::<4>(),
            set::<4, A>(),
            set::<5, B>(),
            set::<5, C>(),
            set::<5, D>(),
            set::<5, E>(),
            set::<5, H>(),
            set::<5, L>(),
            set_hlmem::<5>(),
            set::<5, A>(),
            set::<6, B>(),
            set::<6, C>(),
            set::<6, D>(),
            set::<6, E>(),
            set::<6, H>(),
            set::<6, L>(),
            set_hlmem::<6>(),
            set::<6, A>(),
            set::<7, B>(),
            set::<7, C>(),
            set::<7, D>(),
            set::<7, E>(),
            set::<7, H>(),
            set::<7, L>(),
            set_hlmem::<7>(),
            set::<7, A>(),
        ]
    }

    pub(in crate::cpu) fn get(&mut self, opcode: InstructionOpcode) -> &mut Instruction {
        match opcode {
            InstructionOpcode::Unprefixed(opcode) => &mut self.instructions[opcode as usize],
            InstructionOpcode::Prefixed(opcode) => &mut self.cb_instructions[opcode as usize],
            InstructionOpcode::InterruptServiceRoutine => &mut self.interrupt_service_routine,
        }
    }
}
