name: Rust

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: checkout repo
        uses: actions/checkout@v3

      - name: setup python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: run download_test_roms script
        run: |
          python ./scripts/download_test_roms.py

      - name: Build
        run: cargo build --verbose

      - name: Run tests
        run: cargo test --verbose
